services:
  external:
    container_name: external-api
    build:
      context: ../services/external
      dockerfile: ./src/main/container/Containerfile.temurin
    healthcheck:
      test: |
        wget \
          --spider \
          http://localhost:8080/q/health \
          1>/dev/null 2>/dev/null \
          || exit 1
      interval: 3s
      timeout: 1s
      retries: 3
    environment:
      QUARKUS_HTTP_PORT: 8080
  internal:
    container_name: service
    build:
      context: ../services/internal
      dockerfile: ./src/main/container/Containerfile.temurin
    environment:
      EXTERNAL_API_URL: http://citrus-tests:8080
      QUARKUS_HTTP_PORT: 8080
    healthcheck:
      test: |
        wget \
          --spider \
          http://localhost:8080/q/health \
          1>/dev/null 2>/dev/null \
          || exit 1
      interval: 3s
      timeout: 1s
      retries: 3
  citrus:
    container_name: citrus-tests
    image: quay.io/citrusframework/citrus-agent:4.6.0
    environment:
      CITRUS_AGENT_NAME: citrus-proxy-tests
      CITRUS_AGENT_SKIP_TESTS: true
      CITRUS_AGENT_TEST_JAR: /deployments/resources/citrus-tests.jar
      CITRUS_LOG_DIR: /deployments/data/citrus-reports/
      CITRUS_TEST_ACTOR_CALL_SUT_ENABLED: true
      CITRUS_TEST_ACTOR_EXTERNAL_API_ENABLED: true
      CITRUS_TEST_ACTOR_VERIFY_EXTERNAL_API_ENABLED: true
      EXTERNAL_API_URL: http://external:8080
      HTTP_SERVER_PORT: 8080
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      SUT_URL: http://internal:8080
    volumes:
      - ../citrus/target/citrus-999-SNAPSHOT-citrus-tests.jar:/deployments/resources/citrus-tests.jar:ro
      - ../citrus/src/test/resources/log4j2.properties:/deployments/resources/log4j2.properties
    ports:
      - '4567:4567'
      - '5006:5005'
    depends_on:
      external:
        condition: service_healthy
      internal:
        condition: service_healthy
    healthcheck:
      test: |
        curl \
          --fail \
          http://localhost:4567/health \
          1>/dev/null 2>/dev/null \
          || exit 1
      interval: 3s
      timeout: 1s
      retries: 3